import type { Space, RoleConfig, EventItem, ActivityCategory, EventState, ContractType } from '../domain/types';

export const VIRLA_SPACES: Space[] = [
  {
    id: 'teatro-300',
    name: 'Sala de Teatro (300 butacas)',
    shortName: 'Teatro 300',
    capacity: 300,
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    description: 'Sala principal con escenario italiano, cabina de sonido e iluminación, y 300 plateas.',
  },
  {
    id: 'subsuelo-muestras',
    name: 'Sala de Muestras (Subsuelo)',
    shortName: 'Subsuelo Expos',
    capacity: 120,
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    description: 'Espacio curatorial para artes visuales, fotografía, escultura y montajes artísticos.',
  },
  {
    id: 'bar',
    name: 'Bar Cultural y Patio',
    shortName: 'Bar / Patio',
    capacity: 80,
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    description: 'Área gastronómica y acústica informal para recitales de cámara, café literario y charlas.',
  },
  {
    id: 'radio',
    name: 'Estudio Radio Universidad',
    shortName: 'Radio UNT',
    capacity: 15,
    badgeColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    description: 'Estudio de radiodifusión en vivo y streaming para programas especiales y coberturas.',
  },
  {
    id: 'boleteria',
    name: 'Boletería del Virla',
    shortName: 'Boletería',
    capacity: undefined,
    badgeColor: 'bg-slate-100 text-slate-800 border-slate-300',
    description: 'Punto de atención para venta presencial y liquidación de taquilla.',
  },
  {
    id: 'recepcion',
    name: 'Recepción y Hall Central',
    shortName: 'Recepción',
    capacity: 100,
    badgeColor: 'bg-stone-100 text-stone-800 border-stone-300',
    description: 'Ingreso al centro cultural, control de acceso y entrega de información al público.',
  },
];

export const ROLE_CONFIGS: Record<string, RoleConfig> = {
  DIRECCION: {
    id: 'DIRECCION',
    title: 'Dirección General',
    personName: 'Director del Virla',
    badge: 'bg-[#003865] text-white',
    description: 'Supervisión general, aprobación de contratos y control de agenda central.',
  },
  EXTENSION: {
    id: 'EXTENSION',
    title: 'Secretaría de Extensión UNT',
    personName: 'Marcelo Mirkin',
    badge: 'bg-[#007F8C] text-white',
    description: 'Gestión y reserva de fechas de extensión universitaria y convenios institucionales.',
  },
  COMUNICACION: {
    id: 'COMUNICACION',
    title: 'Prensa & Difusión',
    personName: 'Equipo de Comunicación',
    badge: 'bg-[#2A87AB] text-white',
    description: 'Seguimiento de material gráfico, gacetillas de prensa y contacto por WhatsApp.',
  },
  MUESTRAS: {
    id: 'MUESTRAS',
    title: 'Muestras y Exposiciones',
    personName: 'Curador y Montaje (Subsuelo)',
    badge: 'bg-[#295B88] text-white',
    description: 'Planificación de montajes, inauguraciones y desmontajes de obras plásticas.',
  },
  BOLETERIA_WEB: {
    id: 'BOLETERIA_WEB',
    title: 'Boletería & Web',
    personName: 'Comodín de Entradas y Web',
    badge: 'bg-[#3F82BC] text-white',
    description: 'Carga de tarifas, promociones, condiciones y publicación en la web institucional.',
  },
  RECEPCION: {
    id: 'RECEPCION',
    title: 'Recepción & Sala',
    personName: 'Mesa de Entrada y Seguridad',
    badge: 'bg-slate-700 text-slate-100',
    description: 'Impresión y distribución semanal de la agenda de los viernes para el personal.',
  },
};

export const CATEGORY_COLORS: Record<ActivityCategory, { label: string; badge: string; border: string; text: string; bg: string }> = {
  TEATRO: {
    label: 'Teatro',
    badge: 'bg-emerald-500 text-white',
    border: 'border-emerald-500',
    text: 'text-emerald-700',
    bg: 'bg-emerald-50',
  },
  UNIVERSITARIO: {
    label: 'Actividad Universitaria UNT',
    badge: 'bg-blue-600 text-white',
    border: 'border-blue-600',
    text: 'text-blue-700',
    bg: 'bg-blue-50',
  },
  MUESTRA: {
    label: 'Muestras y Artes Visuales',
    badge: 'bg-indigo-600 text-white',
    border: 'border-indigo-600',
    text: 'text-indigo-700',
    bg: 'bg-indigo-50',
  },
  MUSICA: {
    label: 'Música en Vivo',
    badge: 'bg-fuchsia-600 text-white',
    border: 'border-fuchsia-600',
    text: 'text-fuchsia-700',
    bg: 'bg-fuchsia-50',
  },
  DANZA: {
    label: 'Danza',
    badge: 'bg-rose-500 text-white',
    border: 'border-rose-500',
    text: 'text-rose-700',
    bg: 'bg-rose-50',
  },
  CONFERENCIA: {
    label: 'Conferencia / Presentación',
    badge: 'bg-amber-600 text-white',
    border: 'border-amber-600',
    text: 'text-amber-700',
    bg: 'bg-amber-50',
  },
  RADIO_ENVIVO: {
    label: 'Radio en Vivo',
    badge: 'bg-cyan-600 text-white',
    border: 'border-cyan-600',
    text: 'text-cyan-700',
    bg: 'bg-cyan-50',
  },
};

export const STATE_LABELS: Record<EventState, { label: string; badge: string }> = {
  SOLICITUD: { label: 'Nota / Solicitud', badge: 'bg-gray-200 text-gray-800' },
  RESERVA_PROVISORIA: { label: 'Reserva Provisoria', badge: 'bg-amber-200 text-amber-900 border border-amber-400' },
  CONTRATO_EMITIDO: { label: 'Contrato Emitido', badge: 'bg-blue-200 text-blue-900 border border-blue-400' },
  EN_PRODUCCION: { label: 'En Producción / Prensa', badge: 'bg-purple-200 text-purple-900 border border-purple-400' },
  CONFIRMADO: { label: 'Confirmado', badge: 'bg-emerald-200 text-emerald-900 border border-emerald-400 font-semibold' },
  REALIZADO: { label: 'Realizado', badge: 'bg-slate-200 text-slate-700' },
  CANCELADO: { label: 'Cancelado', badge: 'bg-rose-200 text-rose-900 line-through' },
};

export const CONTRACT_LABELS: Record<ContractType, string> = {
  ALQUILER_SALA: 'Alquiler de Sala (Con Costo)',
  ALQUILER_SIN_COSTO: 'Alquiler Sin Costo (Institucional)',
  ACTIVIDAD_UNIVERSITARIA: 'Actividad Universitaria UNT',
  COPRODUCCION: 'Coproducción (% Borderaux)',
  MUESTRA_EXPOSICION: 'Régimen de Exposición Artística',
  OTRO: 'Otro Tipo de Acuerdo',
};

export const INITIAL_EVENTS: EventItem[] = [
  {
    id: 'evt-1',
    title: 'Obra Teatral: "La Lección de Anatomía"',
    description: 'Compañía tucumana de teatro independiente. Puesta en escena con 8 actores.',
    spaceId: 'teatro-300',
    category: 'TEATRO',
    state: 'CONTRATO_EMITIDO',
    contractType: 'ALQUILER_SALA',
    startDate: '2026-09-11T21:00',
    endDate: '2026-09-11T23:00',
    responsible: {
      name: 'Mariano Albornoz',
      phone: '3814892211',
      email: 'mariano.albornoz@gmail.com',
      organization: 'Grupo Teatral Espejo',
    },
    communication: {
      hasPhotos: true,
      hasPressRelease: false,
      hasLogo: true,
      hasSocialCopy: false,
      notes: 'Falta gacetilla de prensa y ficha técnica de iluminación para redes.',
      lastContactedAt: '2026-09-02',
    },
    exhibition: {
      isExhibition: false,
    },
    ticketing: {
      isFree: false,
      priceGeneral: 8000,
      priceStudentDiscount: 6000,
      saleConditions: 'Venta anticipada por Boletería y web del Virla. 10% descuento jubilados.',
      isPublishedOnWeb: true,
      ticketLink: 'https://virla.unt.edu.ar/entradas/la-leccion',
    },
    audit: {
      createdByRole: 'DIRECCION',
      createdByName: 'Dirección Virla',
      isExtensionAgreement: false,
      acknowledgedByDirector: true,
      createdAt: '2026-08-20T10:30:00Z',
      updatedAt: '2026-09-01T14:15:00Z',
    },
  },
  {
    id: 'evt-2',
    title: 'Muestra Visual: "Horizontes del Aconquija"',
    description: 'Retrospectiva fotográfica y escultura textil de artistas del Valle de Tafí.',
    spaceId: 'subsuelo-muestras',
    category: 'MUESTRA',
    state: 'CONFIRMADO',
    contractType: 'MUESTRA_EXPOSICION',
    startDate: '2026-09-08T19:00',
    endDate: '2026-09-22T21:00',
    responsible: {
      name: 'Lic. Clara Silvetti',
      phone: '3815993344',
      email: 'clara.silvetti@artistasnoa.org',
      organization: 'Colectivo de Arte NOA',
    },
    communication: {
      hasPhotos: true,
      hasPressRelease: true,
      hasLogo: true,
      hasSocialCopy: true,
      notes: 'Kit de prensa completo recibido. Publicado en gacetilla oficial de la UNT.',
      lastContactedAt: '2026-09-03',
    },
    exhibition: {
      isExhibition: true,
      mountingStart: '2026-09-06',
      mountingEnd: '2026-09-07',
      vernissage: '2026-09-08T19:30',
      unmountingDate: '2026-09-23',
      curator: 'Prof. Gabriel Quinteros',
    },
    ticketing: {
      isFree: true,
      saleConditions: 'Entrada libre y gratuita. Visitas de lunes a viernes de 9 a 13 y 17 a 21 hs.',
      isPublishedOnWeb: true,
      ticketLink: 'https://virla.unt.edu.ar/muestras/aconquija',
    },
    audit: {
      createdByRole: 'MUESTRAS',
      createdByName: 'Prof. Gabriel Quinteros (Encargado Expos)',
      isExtensionAgreement: false,
      acknowledgedByDirector: true,
      createdAt: '2026-08-15T09:00:00Z',
      updatedAt: '2026-09-02T11:20:00Z',
    },
  },
  {
    id: 'evt-3',
    title: 'Jornada Universitaria: "Desafíos de la Extensión en el NOA"',
    description: 'Encuentro con decanos, secretarios y cátedras de toda la UNT para debate institucional.',
    spaceId: 'teatro-300',
    category: 'UNIVERSITARIO',
    state: 'RESERVA_PROVISORIA',
    contractType: 'ACTIVIDAD_UNIVERSITARIA',
    startDate: '2026-09-15T09:00',
    endDate: '2026-09-15T14:00',
    responsible: {
      name: 'Marcelo Mirkin',
      phone: '3816223399',
      email: 'mmirkin@extension.unt.edu.ar',
      organization: 'Secretaría de Extensión Universitaria UNT',
    },
    communication: {
      hasPhotos: false,
      hasPressRelease: true,
      hasLogo: true,
      hasSocialCopy: false,
      notes: 'Falta flyer final aprobado por Prensa Rectorado.',
    },
    exhibition: {
      isExhibition: false,
    },
    ticketing: {
      isFree: true,
      saleConditions: 'Actividad académica oficial UNT. Ingreso libre hasta agotar capacidad.',
      isPublishedOnWeb: false,
    },
    audit: {
      createdByRole: 'EXTENSION',
      createdByName: 'Marcelo Mirkin (Secretaría de Extensión)',
      isExtensionAgreement: true, // ALERTA: Acordado por Extensión sin visto bueno previo del Director
      acknowledgedByDirector: false,
      directorNotes: 'Revisar superposición con ensayo técnico de la tarde.',
      createdAt: '2026-09-04T12:00:00Z',
      updatedAt: '2026-09-04T12:00:00Z',
    },
  },
  {
    id: 'evt-4',
    title: 'Ciclo Acústico: "Guitarras Tucumanas en el Bar"',
    description: 'Trío folclórico instrumental en el bar del Virla con degustación de vinos regionales.',
    spaceId: 'bar',
    category: 'MUSICA',
    state: 'EN_PRODUCCION',
    contractType: 'COPRODUCCION',
    startDate: '2026-09-12T21:30',
    endDate: '2026-09-12T23:45',
    responsible: {
      name: 'Ramiro Martínez',
      phone: '3813445566',
      email: 'ramiro.guitarras@yahoo.com.ar',
      organization: 'Trío Manantial',
    },
    communication: {
      hasPhotos: false,
      hasPressRelease: false,
      hasLogo: false,
      hasSocialCopy: false,
      notes: 'URGENTE: El responsable no contestó los pedidos de foto y biografía para cartelera.',
      lastContactedAt: '2026-08-28',
    },
    exhibition: {
      isExhibition: false,
    },
    ticketing: {
      isFree: false,
      priceGeneral: 5000,
      saleConditions: 'Derecho de espectáculo consumición opcional en el Bar del Virla.',
      isPublishedOnWeb: false,
    },
    audit: {
      createdByRole: 'DIRECCION',
      createdByName: 'Dirección Virla',
      isExtensionAgreement: false,
      acknowledgedByDirector: true,
      createdAt: '2026-08-25T16:00:00Z',
      updatedAt: '2026-09-03T18:00:00Z',
    },
  },
  {
    id: 'evt-5',
    title: 'Transmisión Especial: "La UNT y la Comunidad"',
    description: 'Programa radial en vivo desde el estudio del Virla con entrevistas a directores de teatro.',
    spaceId: 'radio',
    category: 'RADIO_ENVIVO',
    state: 'CONFIRMADO',
    contractType: 'ALQUILER_SIN_COSTO',
    startDate: '2026-09-10T10:00',
    endDate: '2026-09-10T12:30',
    responsible: {
      name: 'Florencia Paz',
      phone: '3814112233',
      email: 'radiount@prensa.unt.edu.ar',
      organization: 'Radio Universidad 94.7',
    },
    communication: {
      hasPhotos: true,
      hasPressRelease: true,
      hasLogo: true,
      hasSocialCopy: true,
      notes: 'Pautas de difusión emitidas por frecuencia de Radio Universidad.',
    },
    exhibition: {
      isExhibition: false,
    },
    ticketing: {
      isFree: true,
      saleConditions: 'Emisión radial y streaming web institucional.',
      isPublishedOnWeb: true,
    },
    audit: {
      createdByRole: 'DIRECCION',
      createdByName: 'Dirección Virla',
      isExtensionAgreement: false,
      acknowledgedByDirector: true,
      createdAt: '2026-08-10T11:00:00Z',
      updatedAt: '2026-09-02T09:00:00Z',
    },
  },
  {
    id: 'evt-6',
    title: 'Presentación del Libro: "Memorias del Teatro del Norte"',
    description: 'Presentación a cargo del autor con panel de debate y vino de honor.',
    spaceId: 'bar',
    category: 'CONFERENCIA',
    state: 'SOLICITUD',
    contractType: 'ALQUILER_SIN_COSTO',
    startDate: '2026-09-17T19:00',
    endDate: '2026-09-17T21:00',
    responsible: {
      name: 'Dr. Roberto Carrizo',
      phone: '3815667788',
      email: 'rcarrizo@filo.unt.edu.ar',
      organization: 'Facultad de Filosofía y Letras UNT',
    },
    communication: {
      hasPhotos: false,
      hasPressRelease: false,
      hasLogo: false,
      hasSocialCopy: false,
      notes: 'Presentó nota por mesa de entradas el 03/09. En revisión de fecha.',
    },
    exhibition: {
      isExhibition: false,
    },
    ticketing: {
      isFree: true,
      saleConditions: 'Entrada libre sujeta a capacidad del Bar.',
      isPublishedOnWeb: false,
    },
    audit: {
      createdByRole: 'RECEPCION',
      createdByName: 'Mesa de Entradas / Recepción',
      isExtensionAgreement: false,
      acknowledgedByDirector: false,
      createdAt: '2026-09-03T11:15:00Z',
      updatedAt: '2026-09-03T11:15:00Z',
    },
  },
];
