import { ArrowRight, ArrowUpRight, MapPin, Phone } from 'lucide-react';

const official = 'https://secretariaextension.unt.edu.ar/virla/';
export function InstitutionalLanding() {
  return <div className="institutional-site">
    <a className="skip-link" href="#cultura">Ir al contenido</a>
    <div className="institutional-strip">Universidad Nacional de Tucumán <span>Secretaría de Extensión Universitaria</span></div>
    <header className="public-header"><a className="public-brand" href="#portada" aria-label="Virla, inicio"><strong>VIRLA<span>Centro Cultural</span></strong></a><nav aria-label="Sitio institucional"><a href="#cultura">El Virla</a><a href="#encuentros">Cultura y encuentros</a><a href="#contacto">Contacto</a></nav><a className="public-access" href="#inicio">Acceso del equipo <ArrowUpRight size={17}/></a></header>
    <main>
      <section className="public-hero" id="portada"><img className="public-hero-photo" src="/institutional/fachada.jpg" alt="Fachada del Centro Cultural Virla en 25 de Mayo 265" fetchPriority="high"/><div className="public-hero-copy"><p className="public-kicker">ARTE · UNIVERSIDAD · COMUNIDAD</p><h1>La cultura<br/>nos encuentra.</h1><p>Centro Cultural Eugenio Flavio Virla.<br/>Un espacio de la UNT para vivir el arte en Tucumán.</p><a className="public-button" href="https://elvirla.entradanet.com">Ver programación y entradas <ArrowUpRight size={20}/></a></div><div className="hero-address"><MapPin size={18}/>25 de Mayo 265 · San Miguel de Tucumán</div></section>
      <section className="public-intro public-section" id="cultura"><div><p className="public-kicker">EL VIRLA</p><h2>Un lugar para crear.<br/>Un lugar para compartir.</h2></div><div><p>Desde su inauguración, el 26 de octubre de 1984, el Virla reúne expresiones artísticas y actividades de la comunidad universitaria.</p><p>Artes visuales, teatro, música y literatura conviven con talleres, conferencias y presentaciones de libros durante todo el año.</p><a className="public-text-link" href={official}>Conocé nuestra historia en la UNT <ArrowUpRight size={18}/></a></div></section>
      <section className="public-section public-culture" id="encuentros"><div className="public-section-title"><div><p className="public-kicker">CULTURA EN MOVIMIENTO</p><h2>Muchas formas de encontrarnos.</h2></div><a className="public-text-link" href="https://elvirla.entradanet.com">Consultar programación <ArrowRight size={18}/></a></div><div className="public-gallery">
        <article><img src="/institutional/cultura.jpg" alt="Instalación artística exhibida en el Virla" loading="lazy" width="2560" height="1707"/><span>01 / ARTES VISUALES</span><h3>Miradas que se cruzan</h3><p>Muestras y exposiciones para descubrir otras perspectivas.</p></article>
        <article><img src="/institutional/sala.jpg" alt="Encuentro musical frente al Centro Cultural Virla" loading="lazy" width="2560" height="1707"/><span>02 / MÚSICA Y ESCENA</span><h3>El arte se vive en comunidad</h3><p>Teatro y música que acercan artistas y públicos.</p></article>
        <article><img src="/institutional/muestra.jpg" alt="Visitantes recorriendo una exposición textil en el Virla" loading="lazy" width="2560" height="1707"/><span>03 / ENCUENTROS</span><h3>Ideas que nos reúnen</h3><p>Literatura, talleres y conversaciones para seguir aprendiendo.</p></article>
      </div><p className="public-photo-credit">Imágenes del archivo institucional de la Secretaría de Extensión UNT. Consultá las actividades vigentes en la programación.</p></section>
      <section className="public-team public-section"><div><p className="public-kicker">EL TRABAJO DETRÁS DE CADA ENCUENTRO</p><h2>Mi Virla, el espacio del equipo.</h2><p>Agenda, salas y solicitudes en un mismo lugar.</p></div><a className="public-button" href="#inicio">Ingresar a la app <ArrowRight size={20}/></a></section>
      <section className="public-contact public-section" id="contacto"><div><p className="public-kicker">VENÍ AL VIRLA</p><h2>Estamos cerca.</h2><p>25 de Mayo 265<br/>San Miguel de Tucumán · Tucumán</p><a className="public-text-link" href="https://www.google.com/maps/search/?api=1&query=Centro+Cultural+Virla+25+de+Mayo+265+Tucuman"><MapPin size={18}/>Cómo llegar <ArrowUpRight size={18}/></a><a className="public-text-link" href="tel:+543814221692"><Phone size={18}/>(381) 422-1692</a></div><div className="public-contact-links">{[['Programación','programacionvirla@gmail.com'],['Muestras','muestrasvirla@gmail.com'],['Prensa','prensavirla@gmail.com'],['La Tienda Virla','latiendavirla@gmail.com']].map(([label,email])=><a key={email} href={`mailto:${email}`}><span>{label}<small>{email}</small></span><ArrowUpRight size={23}/></a>)}</div></section>
    </main><footer className="public-footer"><img src="/institutional/marca.png" alt="Centro Cultural Eugenio Flavio Virla" width="240" height="144"/><div><strong>Universidad Nacional de Tucumán</strong><p>Secretaría de Extensión Universitaria</p><a href={official}>Sitio institucional UNT <ArrowUpRight size={15}/></a></div><a href="#inicio">Acceso del equipo</a></footer>
  </div>;
}
